create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    type text not null,
    title text,
    message text not null,
    data jsonb not null default '{}'::jsonb,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'notifications'
          and policyname = 'allow service_role insert'
    ) then
        create policy "allow service_role insert"
            on public.notifications
            for insert
            to service_role
            with check (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_publication_rel pr
        join pg_class c on c.oid = pr.prrelid
        join pg_namespace n on n.oid = c.relnamespace
        where pr.prpubid = 'supabase_realtime'::regpublication
          and n.nspname = 'public'
          and c.relname = 'notifications'
    ) then
        alter publication supabase_realtime add table public.notifications;
    end if;
end
$$;